# This file is auto-generated by the release workflow. Do not edit by hand.
class KojacoordProxy < Formula
  desc "High-performance Minecraft proxy"
  homepage "https://github.com/aleroycz/kojacoord"
  version "0.1.11"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.11/kojacoord-proxy-macos-aarch64"
      sha256 "c39faf56f0796946ccd1e9578cdacad1725de10abda9592af930597b387ca8ef"
    end
    on_intel do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.11/kojacoord-proxy-macos-x86_64"
      sha256 "0da3449ec3ff546b99ab94e675170a1a8937b638ff0f91a2b52d14e70629241b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.11/kojacoord-proxy-linux-aarch64"
      sha256 "deae73467764a65db1997865c1bedfd5d86497a1b8b218de8fb1c52aa492aa2e"
    end
    on_intel do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.11/kojacoord-proxy-linux-x86_64"
      sha256 "a1e366be77024716a1281f9a40e05a18a509eecee6fcee80bb19befc52070e7e"
    end
  end

  def install
    bin.install Dir["kojacoord-proxy-*"].first => "kojacoord-proxy"
  end

  test do
    assert_match "kojacoord", shell_output("#{bin}/kojacoord-proxy --help 2>&1", 2)
  end
end
