# This file is auto-generated by the release workflow. Do not edit by hand.
class KojacoordProxy < Formula
  desc "High-performance Minecraft proxy"
  homepage "https://github.com/aleroycz/kojacoord"
  version "0.1.9"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.9/kojacoord-proxy-macos-aarch64"
      sha256 "39c855bc706f87613f63f4a87f98bb541b71d6a3b39662b4649faf9a06be63ad"
    end
    on_intel do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.9/kojacoord-proxy-macos-x86_64"
      sha256 "06a8038768b3e915cd3873d60e41c276366c0fdf3053bd0c646b6fa1ac0ba4ec"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.9/kojacoord-proxy-linux-aarch64"
      sha256 "302bd2ac232890825084878b58689203b5bcaeee727b3628924a7ac63a376bb9"
    end
    on_intel do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.9/kojacoord-proxy-linux-x86_64"
      sha256 "fc42a6fd0ea2c1f3d647980dd033345c98c4eff973aa996e39a3be5b9cb16ba2"
    end
  end

  def install
    bin.install Dir["kojacoord-proxy-*"].first => "kojacoord-proxy"
  end

  test do
    assert_match "kojacoord", shell_output("#{bin}/kojacoord-proxy --help 2>&1", 2)
  end
end
