# This file is auto-generated by the release workflow. Do not edit by hand.
class KojacoordProxy < Formula
  desc "High-performance Minecraft proxy"
  homepage "https://github.com/aleroycz/kojacoord"
  version "0.1.10"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.10/kojacoord-proxy-macos-aarch64"
      sha256 "dd7634390c165dc8ca7f9496e31c21a9fa912ca3395c7c459cabfed0e3f6816a"
    end
    on_intel do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.10/kojacoord-proxy-macos-x86_64"
      sha256 "64500689e2abc4bc5ef9a8bf2cf5bb94139832de909937823c0c44e3989fb3dc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.10/kojacoord-proxy-linux-aarch64"
      sha256 "31ab1d30248e27d7f13856e12c12801cfd0bab1bc505f5c7ebf8d1973ed5e1be"
    end
    on_intel do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.10/kojacoord-proxy-linux-x86_64"
      sha256 "d572f7a4695687f009001f84bd071eb5a1ed1852d22baf9ffde1883276a3083a"
    end
  end

  def install
    bin.install Dir["kojacoord-proxy-*"].first => "kojacoord-proxy"
  end

  test do
    assert_match "kojacoord", shell_output("#{bin}/kojacoord-proxy --help 2>&1", 2)
  end
end
